###
# -------------------------------------------------------------
# --------------------------UserRoutes-------------------------
# -------------------------------------------------------------

# UserLogin
###
POST  http://localhost:5000/api/user/login
content-type: application/json

{
    "email":"roop@gmail.com",
    "password":"123456789"
}

# Get User Details Passing Bearer token
###
GET  http://localhost:5000/api/user/getdetails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUxNWExMjY0MGQwNDA4ODgwZDVlYTUyIiwiZW1haWwiOiJyb29wQGdtYWlsLmNvbSIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5Njc1NzYzMiwiZXhwIjoxNjk2ODQ0MDMyfQ.eXIPntc2L_pVkdi-X-T4xWPE-O8jn6yv10yXH79mbUg


# Get User Details Passing _id/email with status as query param
###
GET  http://localhost:5000/api/user/details
    ?email=roop@gmail.com

# Update User Security Question Passing Bearer token
###
PUT  http://localhost:5000/api/user/update/security-question
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUxNWExMjY0MGQwNDA4ODgwZDVlYTUyIiwiZW1haWwiOiJyb29wQGdtYWlsLmNvbSIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5Njc1NzYzMiwiZXhwIjoxNjk2ODQ0MDMyfQ.eXIPntc2L_pVkdi-X-T4xWPE-O8jn6yv10yXH79mbUg

{
    "questionId":"65227ae06b3f85a4db705d2c",
    "answer":"Roop"
}

# TODO still testing the file upload api call here
# Update User profile picture Passing Bearer token
###
PUT  http://localhost:5000/api/user/updateImage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUxNWE3ZjI0NzdmYWZjMjZiYjA4ZDUzIiwiZW1haWwiOiJyb29wY29udHJhY3RvckBnbWFpbC5jb20iLCJyb2xlIjoiY29udHJhY3RvciIsImlhdCI6MTY5Njg4MTkzMywiZXhwIjoxNjk2OTY4MzMzfQ.90Sn9bYuIeAHjwIe8NmTMiFOO5rJLKwhbe8eUPrWl6A
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="profilePic"; filename="indirabg.png"
Content-Type: image/png

< ./indirabg.png
------WebKitFormBoundary7MA4YWxkTrZu0gW

# Update User ServicesProviced Passing Bearer token
###
PUT  http://localhost:5000/api/user/add/services
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUxNWExMjY0MGQwNDA4ODgwZDVlYTUyIiwiZW1haWwiOiJyb29wQGdtYWlsLmNvbSIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5Njc1NzYzMiwiZXhwIjoxNjk2ODQ0MDMyfQ.eXIPntc2L_pVkdi-X-T4xWPE-O8jn6yv10yXH79mbUg

{
    "servicesProvided":["Carpenting","Flooring"]
}

# Update User Details Passing Bearer token
###
PUT  http://localhost:5000/api/user/update
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUxNWExMjY0MGQwNDA4ODgwZDVlYTUyIiwiZW1haWwiOiJyb29wQGdtYWlsLmNvbSIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5Njc1NzYzMiwiZXhwIjoxNjk2ODQ0MDMyfQ.eXIPntc2L_pVkdi-X-T4xWPE-O8jn6yv10yXH79mbUg

{
    "phoneNumber":"",
    "fullName":""
}

# Register a user as Owner/porjectManager
###
POST  http://localhost:5000/api/user/register
content-type: application/json

{
    "email":"roop@gmail.com",
    "password":"123456789",
    "fullName":"",
    "phoneNumber":"",
    "organizationName":""
}

# Register a user as contractor(service provider)
###
POST  http://localhost:5000/api/user/register/contractor
content-type: application/json

{
    "email":"roop@gmail.com",
    "password":"123456789",
    "fullName":"",
    "phoneNumber":"",
    "organizationName":""
}

# Add/Register a user as contractor from Owner account Passing Bearer token
###
POST  http://localhost:5000/api/user/add/contractor
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUxNWExMjY0MGQwNDA4ODgwZDVlYTUyIiwiZW1haWwiOiJyb29wQGdtYWlsLmNvbSIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5Njc1NzYzMiwiZXhwIjoxNjk2ODQ0MDMyfQ.eXIPntc2L_pVkdi-X-T4xWPE-O8jn6yv10yXH79mbUg

{
    "email":"roop@gmail.com",
    "password":"123456789",
    "fullName":"",
    "phoneNumber":"",
    "organizationName":""
}

#Reset user password
###
POST  http://localhost:5000/api/user/resetpassword
content-type: application/json

{
    "email":"roop@gmail.com",
    "oldPassword":"123456789",
    "newPassword":"123456789",
}


###
# -------------------------------------------------------------
# ----------------------SecurityQuestions----------------------
# -------------------------------------------------------------

# Create SecurityQuestion
###
POST http://localhost:5000/api/question/add
content-type: application/json

{
    "question":"What is your Name"
}

# Get All SecurityQuestion
###
GET http://localhost:5000/api/question/get

# Get a specific SecurityQuestion by ID
###
GET http://localhost:5000/api/question/get/65227ae06b3f85a4db705d2c


# Update a specific SecurityQuestion by ID
###
PUT http://localhost:5000/api/question/update/65227ae06b3f85a4db705d2c
content-type: application/json

{
    "question":""
}

# Delete a specific SecurityQuestion by ID
###
DELETE http://localhost:5000/api/question/delete/65227ae06b3f85a4db705d2c


###
# -------------------------------------------------------------
# ------------------------ProjectRoutes------------------------
# -------------------------------------------------------------

# Create a Project Passing Bearer token
###
POST http://localhost:5000/api/project/add
# content-type: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUxNWExMjY0MGQwNDA4ODgwZDVlYTUyIiwiZW1haWwiOiJyb29wQGdtYWlsLmNvbSIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5Njc1NzYzMiwiZXhwIjoxNjk2ODQ0MDMyfQ.eXIPntc2L_pVkdi-X-T4xWPE-O8jn6yv10yXH79mbUg
{
    "projectName": "RK tower Cleaning upgarde",
    "projectType": "RenovateAI",
    "clientPhNumber": "9874563210",
    "address": "No 11, 2nd Cross Road, New street",
    "city": "New City1",
    "state": "New State1",
    "country": "NewContryLand1",
    "zipcode": "1007",
    "startDate": "01/10/2022",
    "endDate": "01/5/2023",
    "moveDate": "01/6/2023",
    "serviceNeeded":[],
    "documents":[]
}

# TODO need to add the image and other fields

###
GET http://localhost:5000/api/document/getDocs?userId=63976b12329e59674da31526


###
# -------------------------------------------------------------
# -------------------ProjectContractorRoutes-------------------
# -------------------------------------------------------------


# Add contrator to a project
###
POST http://localhost:5000/api/project/contractor/add
content-type: application/json

{
"projectId":"651dab951bebd70dbc21ffc7",
"contractorId":"6515a7f2477fafc26bb08d53"
}



# get all contractor's project
###
GET http://localhost:5000/api/project/contractor/get-projects
    ?status=completed 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUxNWE3ZjI0NzdmYWZjMjZiYjA4ZDUzIiwiZW1haWwiOiJyb29wY29udHJhY3RvckBnbWFpbC5jb20iLCJyb2xlIjoiY29udHJhY3RvciIsImlhdCI6MTY5Njg4MTkzMywiZXhwIjoxNjk2OTY4MzMzfQ.90Sn9bYuIeAHjwIe8NmTMiFOO5rJLKwhbe8eUPrWl6A
